services:
  web:
    image: portainer/portainer
    environment:
      VIRTUAL_HOST: portainer.127.0.0.1.xip.io
      VIRTUAL_PORT: '9000'
    privileged: true
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:rw
    - ./data:/data:rw
version: '3.0'
networks:
  default:
    external:
      name: services
